name: Build and Deploy to Firebase
on: [push]
jobs:
  buildAndDeploy:
    name: Build
    runs-on: ubuntu-latest
    env:
      CI: false
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      - name: Install and build
        run: |
          yarn install --frozen-lockfile
          yarn build
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@v12.8.0
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
